import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { 
  ArrowLeft, TrendingUp, TrendingDown, DollarSign,
  ArrowUpRight, ArrowDownRight, Download, Check
} from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { financeAPI } from '../services/api';
import { toast } from 'sonner';

const formatCurrency = (amount) => {
  if (Math.abs(amount) >= 100000) {
    return `₹${(amount / 100000).toFixed(2)}L`;
  }
  return `₹${amount.toLocaleString('en-IN')}`;
};

export default function Finance() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    try {
      const response = await financeAPI.getDashboard();
      setData(response.data);
    } catch (error) {
      toast.error('Failed to load finance data');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0a0a]" data-testid="finance-dashboard">
      {/* Header */}
      <header className="sticky top-0 z-50 backdrop-blur-xl bg-[#0a0a0a]/80 border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to="/">
                <Button variant="ghost" size="icon" data-testid="back-btn">
                  <ArrowLeft className="w-5 h-5" />
                </Button>
              </Link>
              <div>
                <h1 className="font-poppins text-xl font-semibold text-white">Finance Dashboard</h1>
                <p className="text-white/60 text-sm">Chief Agent: AG_LAKSHMI • LAKSHMI</p>
              </div>
            </div>
            <Button variant="secondary" size="sm" data-testid="export-csv-btn">
              <Download className="w-4 h-4 mr-2" />
              Export CSV
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        {/* Financial Summary - WP_FIN_NUMERIC_V1.0 enforced */}
        <Card className="p-6 mb-8 border-[#FF6B35]/30 bg-[#FF6B35]/5" data-testid="financial-summary">
          <CardHeader className="px-0 pt-0">
            <div className="flex items-center justify-between">
              <CardTitle>Financial Summary (MTD)</CardTitle>
              <Badge variant="orange">WP_FIN_NUMERIC_V1.0</Badge>
            </div>
          </CardHeader>
          <CardContent className="px-0">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div data-testid="revenue-mtd">
                <p className="text-white/50 text-sm mb-1">Revenue</p>
                <p className="text-3xl font-semibold text-emerald-400">
                  {formatCurrency(data?.revenue_mtd || 1245000)}
                </p>
              </div>
              <div data-testid="expenses-mtd">
                <p className="text-white/50 text-sm mb-1">Expenses</p>
                <p className="text-3xl font-semibold text-red-400">
                  {formatCurrency(data?.expenses_mtd || 823000)}
                </p>
              </div>
              <div data-testid="net-profit">
                <p className="text-white/50 text-sm mb-1">Net Profit</p>
                <p className="text-3xl font-semibold text-white">
                  {formatCurrency(data?.net_profit || 422000)}
                </p>
              </div>
              <div data-testid="margin-percent">
                <p className="text-white/50 text-sm mb-1">Margin</p>
                <p className="text-3xl font-semibold text-[#FF6B35]">
                  {data?.margin_percent || 33.9}%
                </p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-6 mt-6 pt-6 border-t border-white/10">
              <div data-testid="outstanding-receivables">
                <p className="text-white/50 text-sm mb-1">Outstanding Receivables</p>
                <p className="text-2xl font-semibold text-amber-400">
                  {formatCurrency(data?.outstanding_receivables || 289000)}
                </p>
              </div>
              <div data-testid="pending-payables">
                <p className="text-white/50 text-sm mb-1">Pending Payables</p>
                <p className="text-2xl font-semibold text-white/80">
                  {formatCurrency(data?.pending_payables || 156000)}
                </p>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-white/10 text-sm text-white/40">
              <p>Generated by AG_LAKSHMI • Verified by GANESHA ✓</p>
              <p className="font-mono text-xs mt-1">[WP_FIN_NUMERIC_V1.0 • CHK_FIN_NUMERIC_V1.0]</p>
            </div>
          </CardContent>
        </Card>

        {/* Transaction Table */}
        <Card className="p-6" data-testid="transaction-table">
          <CardHeader className="px-0 pt-0">
            <CardTitle>Recent Transactions</CardTitle>
          </CardHeader>
          <CardContent className="px-0">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-white/10">
                    <th className="text-left py-3 px-4 text-white/50 font-medium text-sm">Date</th>
                    <th className="text-left py-3 px-4 text-white/50 font-medium text-sm">Description</th>
                    <th className="text-right py-3 px-4 text-white/50 font-medium text-sm">Amount</th>
                    <th className="text-right py-3 px-4 text-white/50 font-medium text-sm">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {(data?.transactions || [
                    { date: '2025-12-31', description: 'URGAA Revenue', amount: 45000, type: 'credit', status: 'verified' },
                    { date: '2025-12-31', description: 'Workshop Parts', amount: -12500, type: 'debit', status: 'verified' },
                    { date: '2025-12-30', description: 'Training Fees', amount: 18000, type: 'credit', status: 'verified' },
                    { date: '2025-12-30', description: 'Electricity Bill', amount: -8700, type: 'debit', status: 'verified' },
                    { date: '2025-12-29', description: 'GSTSAAS Subscription', amount: 35000, type: 'credit', status: 'verified' },
                  ]).map((tx, index) => (
                    <tr key={index} className="border-b border-white/5 hover:bg-white/5 transition-colors" data-testid={`transaction-${index}`}>
                      <td className="py-3 px-4 text-white/70">{tx.date}</td>
                      <td className="py-3 px-4 text-white">{tx.description}</td>
                      <td className={`py-3 px-4 text-right font-medium ${tx.amount > 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                        <span className="inline-flex items-center gap-1">
                          {tx.amount > 0 ? <ArrowUpRight className="w-4 h-4" /> : <ArrowDownRight className="w-4 h-4" />}
                          {tx.amount > 0 ? '+' : ''}{formatCurrency(tx.amount)}
                        </span>
                      </td>
                      <td className="py-3 px-4 text-right">
                        <Badge variant="success" className="text-xs">
                          <Check className="w-3 h-3 mr-1" />
                          {tx.status}
                        </Badge>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
